### ISSUE TITLE
LED

### ISSUE THREAD

**Issue by Lainkai** [team3487/3487robotCode#19]

**Comment by XanderStraw** [comment]
I want teh lightss!

**Comment by Bjohnson7835** [comment]
`/*----------------------------------------------------------------------------*/
/* Copyright (c) 2017-2018 FIRST. All Rights Reserved.                        */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

package org.usfirst.frc.team1444.robot;

import java.io.Console;

import org.usfirst.frc.team1444.robot.commands.ExampleCommand;
import org.usfirst.frc.team1444.robot.subsystems.ExampleSubsystem;

import com.mach.LightDrive.*;

import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the TimedRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the build.properties file in the
 * project.
 */
public class Robot extends TimedRobot {
	public static final ExampleSubsystem kExampleSubsystem
			= new ExampleSubsystem();
	
	public static OI m_oi;
	
	LightDriveCAN ldrive_can;
	LightDrivePWM ldrive_pwm;
	Servo servo1;
	Servo servo2;

	int counter = 0;
	
	Command m_autonomousCommand;
	SendableChooser<Command> m_chooser = new SendableChooser<>();

	/**
	 * This function is run when the robot is first started up and should be
	 * used for any initialization code.
	 */
	@Override
	public void robotInit() {
		m_oi = new OI();
		
		//Initialize a new CAN LightDrive
		ldrive_can = new LightDriveCAN();
		
		//Initialize 2 Servo outputs for a PWM LightDrive
		servo1 = new Servo(0);
		servo2 = new Servo(1);
		//Initialize a new PWM LightDrive
		ldrive_pwm = new LightDrivePWM(servo1, servo2);
		
		
		m_chooser.addDefault("Default Auto", new ExampleCommand());
		// chooser.addObject("My Auto", new MyAutoCommand());
		SmartDashboard.putData("Auto mode", m_chooser);
	}

	/**
	 * This function is called once each time the robot enters Disabled mode.
	 * You can use it to reset any subsystem information you want to clear when
	 * the robot is disabled.
	 */
	@Override
	public void disabledInit() {
		
		//Set colors on CAN LightDrive, also set brightness (optional)
		ldrive_can.SetColor(1, Color.BLUE, (float) 0.8);
		ldrive_can.SetColor(2, Color.GREEN, (float) 0.8);
		ldrive_can.SetColor(3, Color.RED, (float) 0.8);
		ldrive_can.SetColor(4, Color.YELLOW, (float) 0.8);
		//Send these colors to CAN LightDrive
		//NOTE that we can't call Update() on PWM-controlled LightDrive because
		//PWM output is disabled while robot is disabled.
		ldrive_can.Update();
		
		counter = 0;
	}

	@Override
	public void disabledPeriodic() {
		Scheduler.getInstance().run();
		
		//Rotate through colors on Bank1 of CAN LightDrive		
		//NOTE that we can't call Update() on PWM-controlled LightDrive because
		//PWM output is disabled while robot is disabled.
		if(counter++ < 100)
		{
			ldrive_can.SetColor(1, Color.RED);		
		}
		else if(counter < 200)
		{
			ldrive_can.SetColor(1, Color.GREEN);	
		}
		else if(counter < 400)
		{
			ldrive_can.SetColor(1, Color.BLUE);	
		}
		else if(counter < 600)
		{
			ldrive_can.SetColor(1, Color.YELLOW);	
		}
		else if(counter < 800)
		{
			ldrive_can.SetColor(1, Color.PURPLE);	
		}
		else if(counter < 1000)
		{
			ldrive_can.SetColor(1, Color.TEAL);	
		}
		else if(counter < 1200)
		{
			ldrive_can.SetColor(1, Color.WHITE);
		}
		else if(counter < 1400)
		{
			ldrive_can.SetColor(1, Color.OFF);	
		}
		else if(counter > 1600)
		{
			counter = 0;
		}
		
		//Send latest color settings to CAN LightDrive
		ldrive_can.Update();
		
		//Print Current and Voltage received from CAN LightDrive
		System.out.format("LightDrive Currents: %2.1f %2.1f %2.1f %2.1f %2.1fV\r\n", ldrive_can.GetCurrent(1), ldrive_can.GetCurrent(2), ldrive_can.GetCurrent(3), ldrive_can.GetCurrent(4), ldrive_can.GetVoltage());
	}

	/**
	 * This autonomous (along with the chooser code above) shows how to select
	 * between different autonomous modes using the dashboard. The sendable
	 * chooser code works with the Java SmartDashboard. If you prefer the
	 * LabVIEW Dashboard, remove all of the chooser code and uncomment the
	 * getString code to get the auto name from the text box below the Gyro
	 *
	 * <p>You can add additional auto modes by adding additional commands to the
	 * chooser code above (like the commented example) or additional comparisons
	 * to the switch structure below with additional strings & commands.
	 */
	@Override
	public void autonomousInit() {
		m_autonomousCommand = m_chooser.getSelected();

		/*
		 * String autoSelected = SmartDashboard.getString("Auto Selector",
		 * "Default"); switch(autoSelected) { case "My Auto": autonomousCommand
		 * = new MyAutoCommand(); break; case "Default Auto": default:
		 * autonomousCommand = new ExampleCommand(); break; }
		 */

		// schedule the autonomous command (example)
		if (m_autonomousCommand != null) {
			m_autonomousCommand.start();
		}
	}

	/**
	 * This function is called periodically during autonomous.
	 */
	@Override
	public void autonomousPeriodic() {
		Scheduler.getInstance().run();
	}

	@Override
	public void teleopInit() {
		// This makes sure that the autonomous stops running when
		// teleop starts running. If you want the autonomous to
		// continue until interrupted by another command, remove
		// this line or comment it out.
		if (m_autonomousCommand != null) {
			m_autonomousCommand.cancel();
		}
		
		counter = 0;
	}

	/**
	 * This function is called periodically during operator control.
	 */
	@Override
	public void teleopPeriodic() {
		Scheduler.getInstance().run();
		
		//Rotate through colors on Bank1 of PWM LightDrive		
		if(counter++ < 100)
		{
			ldrive_pwm.SetColor(1, Color.RED);		
		}
		else if(counter < 200)
		{
			ldrive_pwm.SetColor(1, Color.GREEN);	
		}
		else if(counter < 400)
		{
			ldrive_pwm.SetColor(1, Color.BLUE);	
		}
		else if(counter < 600)
		{
			ldrive_pwm.SetColor(1, Color.YELLOW);	
		}
		else if(counter < 800)
		{
			ldrive_pwm.SetColor(1, Color.PURPLE);	
		}
		else if(counter < 1000)
		{
			ldrive_pwm.SetColor(1, Color.TEAL);	
		}
		else if(counter < 1200)
		{
			ldrive_pwm.SetColor(1, Color.WHITE);
		}
		else if(counter < 1400)
		{
			ldrive_pwm.SetColor(1, Color.OFF);	
		}
		else if(counter > 1600)
		{
			counter = 0;
		}
		
		//Write Latest Colors to PWM LightDrive (update PWM outputs)
		ldrive_pwm.Update();
	}

	/**
	 * This function is called periodically during test mode.
	 */
	@Override
	public void testPeriodic() {
	}
}
`

**Comment by Lainkai** [comment]
Please make sure to NOT copy other teams, code, especially if they have copyright. Deriving code from them is fine, but just link their project.

**Comment by bwest328** [comment]
Jake, this is not an issue.  If a team puts code on the internet, they clearly are open to people using it.  Also, no teams are allowed to have copyright, considering that FIRST is an open community and every team has to have essentially the same base for driving.  If they have a physical extension to the RIO, they can copyright that.  Code alone cannot be copywritten.

**Comment by Lainkai** [comment]
It's more of, "I thought this was meant to be a commit" situation.

**Comment by Lainkai** [comment]
Hey, I created a branch for working on the LED Edits as a team. Switch to the branch if you want to make commits towards this, not a personal fork.

**Comment by Lainkai** [comment]
I have made a new repository for these edits. If you want to be a part of them, let me know. The repository is for making updates across both bots. [Link to repo](https://github.com/Lainkai/LightDrive12SerialDrivers)
